M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2025-03-25T09:16:15-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-25T09:16:15-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.0Y0.0
X0.0Y-2.7559
X3.937Y0.0
X3.937Y-2.7559
M30
